version: "3.9"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    command: --server
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: "5432"
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_NAME: test
  database:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
